#!/bin/sh

# prevent keyboard mis-mapping
export XKL_XMODMAP_DISABLE=1

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

xsetroot -solid grey
vncconfig -iconic &
autocutsel -fork

# set cursor
xsetroot -cursor_name left_ptr

# start xmonad
# xrdb ~/.xsession
# exec xmonad

# Start a new session -- for linux
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
dbus-launch xfce4-session &
